/*
 * openScale
 * Copyright (C) 2026 openScale contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.health.openscale.core.bluetooth.scales

import com.google.common.truth.Truth.assertThat
import org.junit.Test
import java.util.Calendar
import java.util.TimeZone

/**
 * Unit tests for [HuaweiAhCh100Handler] — the wire-protocol primitives
 * shared by the Huawei AH100 and CH100 body-fat scales.
 *
 * The fixtures encode three realistic measurements and were generated
 * deterministically by `tools/ch100_decoder/_gen_test_fixtures.py` (see the
 * companion repository linked in the PR). The Python helper and the Kotlin
 * code under test are independent re-implementations of the same v2.5.4
 * Java protocol, so a green test here means both ports agree.
 *
 * The test data point at 97.0 kg / 28.0 % matches the values reported by
 * the user in issue #1280 — the same scenario that the broken 3.x master
 * parser turned into 138 kg / 180 % / year 3084.
 */
class HuaweiAhCh100HandlerTest {

    companion object {
        private const val TEST_MAC = "5C:CA:D3:08:7B:4F"
        private const val TEST_USER_ID = 1

        // Generated by _gen_test_fixtures.py with the constants above.
        private const val EXPECTED_AUTH_TOKEN = "11223344551001"
        private const val EXPECTED_MAGIC_KEY  = "4de8e04c2e5f5d2a980fde3456732156"

        // Plaintext = decrypted, post-XOR-de-obfuscation, v2.5.4 layout.
        private const val FIXTURE_USER_PLAINTEXT  = "01ca031801ea070513080c21021c02"
        private const val FIXTURE_LIGHT_PLAINTEXT = "012802bc00ea07010f071e0a04e801"
        private const val FIXTURE_HEAVY_PLAINTEXT = "0104056001ea070301132d00076402"

        // Frames as they go on the wire: [0xBC, len, 0x0E, ...obfuscated(AES(plaintext))...]
        private const val FIXTURE_USER_FRAME  = "bc100edef702c9bbf2176c755b6eccdd5b92b0"
        private const val FIXTURE_LIGHT_FRAME = "bc100ede15036dbaf2176869547ce7dbaf91b0"
        private const val FIXTURE_HEAVY_FRAME = "bc100ede3904b1bbf2176a67404fedd82392b0"
    }

    // -- Primitives ----------------------------------------------------------

    @Test
    fun `obfuscate is self-inverse`() {
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val data = hex("DEADBEEFCAFEBABE0102030405060708")
        val once = HuaweiAhCh100Handler.obfuscate(data, mac)
        val twice = HuaweiAhCh100Handler.obfuscate(once, mac)
        assertThat(once).isNotEqualTo(data)
        assertThat(twice).isEqualTo(data)
    }

    @Test
    fun `obfuscate with empty MAC is identity`() {
        val data = hex("DEADBEEF")
        assertThat(HuaweiAhCh100Handler.obfuscate(data, ByteArray(0))).isEqualTo(data)
    }

    @Test
    fun `xorChecksum returns parity byte`() {
        val buf = hex("DEADBEEFCAFE")
        val expected = (0xDE xor 0xAD xor 0xBE xor 0xEF xor 0xCA xor 0xFE).toByte()
        assertThat(HuaweiAhCh100Handler.xorChecksum(buf)).isEqualTo(expected)
    }

    @Test
    fun `buildAuthToken array XORs to zero`() {
        val tok = HuaweiAhCh100Handler.buildAuthToken(TEST_USER_ID)
        assertThat(tok).hasLength(7)
        assertThat(HuaweiAhCh100Handler.xorChecksum(tok)).isEqualTo(0.toByte())
        // First 5 bytes are constants, last byte is the userId.
        assertThat(tok.copyOfRange(0, 5)).isEqualTo(hex("1122334455"))
        assertThat(tok[6].toInt() and 0xFF).isEqualTo(TEST_USER_ID)
    }

    @Test
    fun `buildAuthToken matches reference fixture for userId=1`() {
        val tok = HuaweiAhCh100Handler.buildAuthToken(TEST_USER_ID)
        assertThat(toHex(tok)).isEqualTo(EXPECTED_AUTH_TOKEN)
    }

    @Test
    fun `deriveMagicKey produces 16 bytes matching v2 5 4 layout`() {
        val tok = HuaweiAhCh100Handler.buildAuthToken(TEST_USER_ID)
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val mk = HuaweiAhCh100Handler.deriveMagicKey(tok, mac)
        assertThat(mk).hasLength(16)
        // First 7 bytes = obfuscate(authToken, MAC).
        assertThat(mk.copyOfRange(0, 7)).isEqualTo(HuaweiAhCh100Handler.obfuscate(tok, mac))
        // Last 9 bytes = INITIAL_KEY[7..15].
        assertThat(mk.copyOfRange(7, 16))
            .isEqualTo(HuaweiAhCh100Handler.INITIAL_KEY.copyOfRange(7, 16))
        assertThat(toHex(mk)).isEqualTo(EXPECTED_MAGIC_KEY)
    }

    @Test
    fun `aesCtr is symmetric`() {
        val key = HuaweiAhCh100Handler.hexToBytes(EXPECTED_MAGIC_KEY)
        val pt = hex("01ca031801ea070513080c21021c02")
        val ct = HuaweiAhCh100Handler.aesCtr(pt, key, HuaweiAhCh100Handler.INITIAL_IV)
        val rt = HuaweiAhCh100Handler.aesCtr(ct, key, HuaweiAhCh100Handler.INITIAL_IV)
        assertThat(ct).isNotEqualTo(pt)
        assertThat(rt).isEqualTo(pt)
    }

    // -- Frame writers -------------------------------------------------------

    @Test
    fun `buildPlainCommand writes len plus 1 in the header byte`() {
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val payload = hex("11223344")
        val frame = HuaweiAhCh100Handler.buildPlainCommand(
            cmd = HuaweiAhCh100Handler.CMD_AUTH,
            payload = payload,
            mac = mac
        )
        // Wire layout: [0xDB, lengthByte, cmd, ...obfuscated payload...]
        assertThat(frame[0]).isEqualTo(HuaweiAhCh100Handler.FRAME_PLAIN)
        assertThat(frame[1].toInt() and 0xFF).isEqualTo(payload.size + 1)
        assertThat(frame[2]).isEqualTo(HuaweiAhCh100Handler.CMD_AUTH)
        assertThat(frame.copyOfRange(3, frame.size))
            .isEqualTo(HuaweiAhCh100Handler.obfuscate(payload, mac))
    }

    @Test
    fun `buildPlainCommand respects explicit length byte for legacy GET_RECORD`() {
        // openScale v2.5.4 sent GET_RECORD with payload of 8 bytes and a wire
        // lengthByte of 0x07 (it called AHsendCommand(_, _, 0x07-1) which then
        // added 1 in the header).
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val payload = hex("1122334455667788")
        val frame = HuaweiAhCh100Handler.buildPlainCommand(
            cmd = HuaweiAhCh100Handler.CMD_GET_RECORD,
            payload = payload,
            mac = mac,
            explicitLen = 0x07
        )
        assertThat(frame[1].toInt() and 0xFF).isEqualTo(0x07)
        assertThat(frame.size).isEqualTo(3 + payload.size)
    }

    @Test
    fun `buildEncryptedCommand uses payload size as length and AES-CTR encrypts`() {
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val mk = HuaweiAhCh100Handler.hexToBytes(EXPECTED_MAGIC_KEY)
        val payload = hex("1122334455667788")
        val frame = HuaweiAhCh100Handler.buildEncryptedCommand(
            cmd = HuaweiAhCh100Handler.CMD_USER_INFO,
            payload = payload,
            magicKey = mk,
            mac = mac
        )
        assertThat(frame[0]).isEqualTo(HuaweiAhCh100Handler.FRAME_ENCRYPTED)
        assertThat(frame[1].toInt() and 0xFF).isEqualTo(payload.size)
        assertThat(frame[2]).isEqualTo(HuaweiAhCh100Handler.CMD_USER_INFO)
        // Recover plaintext: deobfuscate then AES-CTR.
        val deobf = HuaweiAhCh100Handler.obfuscate(frame.copyOfRange(3, frame.size), mac)
        val pt = HuaweiAhCh100Handler.aesCtr(deobf, mk, HuaweiAhCh100Handler.INITIAL_IV)
        assertThat(pt).isEqualTo(payload)
    }

    // -- Measurement decoding ------------------------------------------------

    @Test
    fun `parseMeasurement decodes user fixture (97 kg, 28 percent)`() {
        val m = HuaweiAhCh100Handler.parseMeasurement(hex(FIXTURE_USER_PLAINTEXT))
        assertThat(m.userId).isEqualTo(TEST_USER_ID)
        assertThat(m.weightKg).isWithin(1e-4f).of(97.0f)
        assertThat(m.fatPct).isWithin(1e-4f).of(28.0f)
        assertThat(m.impedanceOhm).isEqualTo(540)
        assertCalendar(m, year = 2026, monthZeroBased = 4, day = 19, hour = 8, minute = 12, second = 33)
    }

    @Test
    fun `parseMeasurement decodes light fixture`() {
        val m = HuaweiAhCh100Handler.parseMeasurement(hex(FIXTURE_LIGHT_PLAINTEXT))
        assertThat(m.userId).isEqualTo(TEST_USER_ID)
        assertThat(m.weightKg).isWithin(1e-4f).of(55.2f)
        assertThat(m.fatPct).isWithin(1e-4f).of(18.8f)
        assertThat(m.impedanceOhm).isEqualTo(488)
        assertCalendar(m, year = 2026, monthZeroBased = 0, day = 15, hour = 7, minute = 30, second = 10)
    }

    @Test
    fun `parseMeasurement decodes heavy fixture`() {
        val m = HuaweiAhCh100Handler.parseMeasurement(hex(FIXTURE_HEAVY_PLAINTEXT))
        assertThat(m.userId).isEqualTo(TEST_USER_ID)
        assertThat(m.weightKg).isWithin(1e-4f).of(128.4f)
        assertThat(m.fatPct).isWithin(1e-4f).of(35.2f)
        assertThat(m.impedanceOhm).isEqualTo(612)
        assertCalendar(m, year = 2026, monthZeroBased = 2, day = 1, hour = 19, minute = 45, second = 0)
    }

    @Test
    fun `parseMeasurement throws on too-short input`() {
        try {
            HuaweiAhCh100Handler.parseMeasurement(hex("00112233"))
            assertThat(false).isTrue() // not reached
        } catch (e: IllegalArgumentException) {
            assertThat(e.message).contains("at least 15 bytes")
        }
    }

    // -- End-to-end frame -> measurement -------------------------------------

    @Test
    fun `decodeFirstHalf round-trips user fixture frame to 97 kg 28 percent`() {
        assertFrameDecodes(
            FIXTURE_USER_FRAME,
            expectedWeight = 97.0f,
            expectedFat = 28.0f,
            expectedImpedance = 540,
        )
    }

    @Test
    fun `decodeFirstHalf round-trips light fixture frame to 55_2 kg 18_8 percent`() {
        assertFrameDecodes(
            FIXTURE_LIGHT_FRAME,
            expectedWeight = 55.2f,
            expectedFat = 18.8f,
            expectedImpedance = 488,
        )
    }

    @Test
    fun `decodeFirstHalf round-trips heavy fixture frame to 128_4 kg 35_2 percent`() {
        assertFrameDecodes(
            FIXTURE_HEAVY_FRAME,
            expectedWeight = 128.4f,
            expectedFat = 35.2f,
            expectedImpedance = 612,
        )
    }

    @Test
    fun `regression - merged 32 byte XOR-only buffer would NOT match (broken 3x)`() {
        // This test pins down the regression we are fixing: the broken 3.x
        // master parser would compute (1457 - byte[1]) / 10 on the raw
        // deobfuscated buffer, which deliberately *does not* equal 97.0.
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val frame = hex(FIXTURE_USER_FRAME)
        val deobfTail = HuaweiAhCh100Handler.deobfuscateTail(frame, mac)
        val brokenWeight = (1457 - (deobfTail[1].toInt() and 0xFF)) / 10.0f
        assertThat(brokenWeight).isNotWithin(1e-4f).of(97.0f)
    }

    // -- Helpers -------------------------------------------------------------

    private fun assertFrameDecodes(
        frameHex: String,
        expectedWeight: Float,
        expectedFat: Float,
        expectedImpedance: Int,
    ) {
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val mk = HuaweiAhCh100Handler.hexToBytes(EXPECTED_MAGIC_KEY)
        val m = HuaweiAhCh100Handler.decodeFirstHalf(hex(frameHex), mk, mac)
        assertThat(m.weightKg).isWithin(1e-4f).of(expectedWeight)
        assertThat(m.fatPct).isWithin(1e-4f).of(expectedFat)
        assertThat(m.impedanceOhm).isEqualTo(expectedImpedance)
        assertThat(m.userId).isEqualTo(TEST_USER_ID)
    }

    private fun assertCalendar(
        m: HuaweiAhCh100Handler.Measurement,
        year: Int, monthZeroBased: Int, day: Int, hour: Int, minute: Int, second: Int
    ) {
        val dt = m.dateTime
        assertThat(dt).isNotNull()
        // The protocol object uses the system default timezone via
        // Calendar.getInstance(); we read fields back the same way to make
        // the assertion timezone-independent.
        val cal = Calendar.getInstance().apply { time = dt!! }
        assertThat(cal.get(Calendar.YEAR)).isEqualTo(year)
        assertThat(cal.get(Calendar.MONTH)).isEqualTo(monthZeroBased)
        assertThat(cal.get(Calendar.DAY_OF_MONTH)).isEqualTo(day)
        assertThat(cal.get(Calendar.HOUR_OF_DAY)).isEqualTo(hour)
        assertThat(cal.get(Calendar.MINUTE)).isEqualTo(minute)
        assertThat(cal.get(Calendar.SECOND)).isEqualTo(second)
    }

    private fun hex(s: String): ByteArray = HuaweiAhCh100Handler.hexToBytes(s)
    private fun toHex(b: ByteArray): String = b.joinToString("") { "%02x".format(it.toInt() and 0xFF) }
}
