/*
 * openScale
 * Copyright (C) 2025 olie.xdev <olie.xdeveloper@googlemail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.health.openscale.ui.theme

import androidx.compose.ui.graphics.Color

val AppBrandBlue = Color(0xFF0099CC)

// === Generated M3 Palette (Seed: #0099CC) ===

// Light
val primaryLight = Color(0xFF1B6585)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC3E8FF)
val onPrimaryContainerLight = Color(0xFF004C68)
val secondaryLight = Color(0xFF4E616D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD1E5F3)
val onSecondaryContainerLight = Color(0xFF364955)
val tertiaryLight = Color(0xFF605A7D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE6DEFF)
val onTertiaryContainerLight = Color(0xFF484264)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF6FAFE)
val onBackgroundLight = Color(0xFF171C1F)
val surfaceLight = Color(0xFFF6FAFE)
val onSurfaceLight = Color(0xFF171C1F)
val surfaceVariantLight = Color(0xFFDCE3E9)
val onSurfaceVariantLight = Color(0xFF41484D)
val outlineLight = Color(0xFF71787D)
val outlineVariantLight = Color(0xFFC0C7CD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3134)
val inverseOnSurfaceLight = Color(0xFFEDF1F5)
val inversePrimaryLight = Color(0xFF8FCFF3)
val surfaceDimLight = Color(0xFFD6DADF)
val surfaceBrightLight = Color(0xFFF6FAFE)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F4F8)
val surfaceContainerLight = Color(0xFFEAEEF2)
val surfaceContainerHighLight = Color(0xFFE5E9ED)
val surfaceContainerHighestLight = Color(0xFFDFE3E7)

// Light Medium Contrast
val primaryLightMediumContrast = Color(0xFF003B51)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF2F7495)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF263943)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF5C707C)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF373252)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF6F688C)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF6FAFE)
val onBackgroundLightMediumContrast = Color(0xFF171C1F)
val surfaceLightMediumContrast = Color(0xFFF6FAFE)
val onSurfaceLightMediumContrast = Color(0xFF0D1215)
val surfaceVariantLightMediumContrast = Color(0xFFDCE3E9)
val onSurfaceVariantLightMediumContrast = Color(0xFF30373C)
val outlineLightMediumContrast = Color(0xFF4C5358)
val outlineVariantLightMediumContrast = Color(0xFF676E73)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2C3134)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEDF1F5)
val inversePrimaryLightMediumContrast = Color(0xFF8FCFF3)
val surfaceDimLightMediumContrast = Color(0xFFC3C7CB)
val surfaceBrightLightMediumContrast = Color(0xFFF6FAFE)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF0F4F8)
val surfaceContainerLightMediumContrast = Color(0xFFE5E9ED)
val surfaceContainerHighLightMediumContrast = Color(0xFFD9DDE1)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCED2D6)

// Light High Contrast
val primaryLightHighContrast = Color(0xFF003043)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004F6B)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF1B2E39)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF394C57)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF2D2847)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF4A4566)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF6FAFE)
val onBackgroundLightHighContrast = Color(0xFF171C1F)
val surfaceLightHighContrast = Color(0xFFF6FAFE)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDCE3E9)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF262D32)
val outlineVariantLightHighContrast = Color(0xFF434A4F)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2C3134)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF8FCFF3)
val surfaceDimLightHighContrast = Color(0xFFB5B9BD)
val surfaceBrightLightHighContrast = Color(0xFFF6FAFE)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEDF1F5)
val surfaceContainerLightHighContrast = Color(0xFFDFE3E7)
val surfaceContainerHighLightHighContrast = Color(0xFFD1D5D9)
val surfaceContainerHighestLightHighContrast = Color(0xFFC3C7CB)

// Dark
val primaryDark = Color(0xFF8FCFF3)
val onPrimaryDark = Color(0xFF003549)
val primaryContainerDark = Color(0xFF004C68)
val onPrimaryContainerDark = Color(0xFFC3E8FF)
val secondaryDark = Color(0xFFB5C9D7)
val onSecondaryDark = Color(0xFF20333D)
val secondaryContainerDark = Color(0xFF364955)
val onSecondaryContainerDark = Color(0xFFD1E5F3)
val tertiaryDark = Color(0xFFC9C1EA)
val onTertiaryDark = Color(0xFF312C4C)
val tertiaryContainerDark = Color(0xFF484264)
val onTertiaryContainerDark = Color(0xFFE6DEFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1417)
val onBackgroundDark = Color(0xFFDFE3E7)
val surfaceDark = Color(0xFF0F1417)
val onSurfaceDark = Color(0xFFDFE3E7)
val surfaceVariantDark = Color(0xFF41484D)
val onSurfaceVariantDark = Color(0xFFC0C7CD)
val outlineDark = Color(0xFF8A9297)
val outlineVariantDark = Color(0xFF41484D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDFE3E7)
val inverseOnSurfaceDark = Color(0xFF2C3134)
val inversePrimaryDark = Color(0xFF1B6585)
val surfaceDimDark = Color(0xFF0F1417)
val surfaceBrightDark = Color(0xFF353A3D)
val surfaceContainerLowestDark = Color(0xFF0A0F12)
val surfaceContainerLowDark = Color(0xFF171C1F)
val surfaceContainerDark = Color(0xFF1C2023)
val surfaceContainerHighDark = Color(0xFF262B2E)
val surfaceContainerHighestDark = Color(0xFF313539)

// Dark Medium Contrast
val primaryDarkMediumContrast = Color(0xFFB4E3FF)
val onPrimaryDarkMediumContrast = Color(0xFF00293A)
val primaryContainerDarkMediumContrast = Color(0xFF5898BA)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFCBDFED)
val onSecondaryDarkMediumContrast = Color(0xFF152832)
val secondaryContainerDarkMediumContrast = Color(0xFF8093A0)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFE0D7FF)
val onTertiaryDarkMediumContrast = Color(0xFF262141)
val tertiaryContainerDarkMediumContrast = Color(0xFF938CB2)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0F1417)
val onBackgroundDarkMediumContrast = Color(0xFFDFE3E7)
val surfaceDarkMediumContrast = Color(0xFF0F1417)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF41484D)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD6DDE3)
val outlineDarkMediumContrast = Color(0xFFACB3B9)
val outlineVariantDarkMediumContrast = Color(0xFF8A9197)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDFE3E7)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF262B2E)
val inversePrimaryDarkMediumContrast = Color(0xFF004E6A)
val surfaceDimDarkMediumContrast = Color(0xFF0F1417)
val surfaceBrightDarkMediumContrast = Color(0xFF404549)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF04080B)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191E21)
val surfaceContainerDarkMediumContrast = Color(0xFF24282C)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2E3336)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3A3E42)

// Dark High Contrast
val primaryDarkHighContrast = Color(0xFFE1F2FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF8BCBEF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000D15)
val secondaryDarkHighContrast = Color(0xFFE1F2FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB1C5D3)
val onSecondaryContainerDarkHighContrast = Color(0xFF000D15)
val tertiaryDarkHighContrast = Color(0xFFF3EDFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC5BDE6)
val onTertiaryContainerDarkHighContrast = Color(0xFF0B0625)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0F1417)
val onBackgroundDarkHighContrast = Color(0xFFDFE3E7)
val surfaceDarkHighContrast = Color(0xFF0F1417)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF41484D)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEAF1F7)
val outlineVariantDarkHighContrast = Color(0xFFBCC3C9)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDFE3E7)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF004E6A)
val surfaceDimDarkHighContrast = Color(0xFF0F1417)
val surfaceBrightDarkHighContrast = Color(0xFF4C5154)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1C2023)
val surfaceContainerDarkHighContrast = Color(0xFF2C3134)
val surfaceContainerHighDarkHighContrast = Color(0xFF373C3F)
val surfaceContainerHighestDarkHighContrast = Color(0xFF43474B)